INSERT INTO bears VALUES(1, 'Mr. Chocolate', NULL, NULL, NULL, NULL, NULL);
INSERT INTO bears VALUES(2, 'Mr. Chocolate', NULL, NULL, NULL, NULL, NULL);
INSERT INTO bears VALUES(3, 'Mr. Chocolate', NULL, NULL, NULL, NULL, NULL);
INSERT INTO bears VALUES(4, 'Mr. Chocolate', NULL, NULL, NULL, NULL, NULL);
INSERT INTO bears VALUES(5, 'Mr. Chocolate', NULL, NULL, NULL, NULL, NULL);
INSERT INTO bears VALUES(6, 'Mr. Chocolate', NULL, NULL, NULL, NULL, NULL);
INSERT INTO bears VALUES(7, 'Mr. Chocolate', NULL, NULL, NULL, NULL, NULL);
INSERT INTO bears VALUES(8, NULL, NULL, NULL, NULL, NULL, NULL);
